CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    classification VARCHAR(20) NOT NULL,
    description TEXT NOT NULL,
    release_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT games_title_unique UNIQUE (title),
    CONSTRAINT games_title_not_blank CHECK (length(trim(title)) > 0),
    CONSTRAINT games_genre_not_blank CHECK (length(trim(genre)) > 0),
    CONSTRAINT games_classification_not_blank CHECK (length(trim(classification)) > 0),
    CONSTRAINT games_description_not_blank CHECK (length(trim(description)) > 0)
);

CREATE TABLE IF NOT EXISTS game_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL,
    game_id BIGINT NOT NULL,
    metric_name VARCHAR(30) NOT NULL,
    metric_value NUMERIC(10, 2) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    measured_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT game_metrics_external_id_unique UNIQUE (external_id),

    CONSTRAINT game_metrics_game_fk
        FOREIGN KEY (game_id)
        REFERENCES games (id)
        ON DELETE RESTRICT,

    CONSTRAINT game_metrics_name_unit_valid CHECK (
        (metric_name = 'duration' AND unit = 'hours')
        OR (metric_name = 'rating' AND unit = 'stars')
    ),

    CONSTRAINT game_metrics_value_valid CHECK (
        (metric_name = 'duration' AND metric_value > 0 AND metric_value <= 10000)
        OR (metric_name = 'rating' AND metric_value >= 0 AND metric_value <= 5)
    )
);

CREATE INDEX IF NOT EXISTS idx_game_metrics_game_id
    ON game_metrics (game_id);

CREATE INDEX IF NOT EXISTS idx_game_metrics_measured_at
    ON game_metrics (measured_at);