CREATE TABLE IF NOT EXISTS platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(80) NOT NULL,
    manufacturer VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT platforms_code_unique UNIQUE (code),
    CONSTRAINT platforms_code_not_blank CHECK (length(trim(code)) > 0),
    CONSTRAINT platforms_name_not_blank CHECK (length(trim(name)) > 0),
    CONSTRAINT platforms_manufacturer_not_blank CHECK (length(trim(manufacturer)) > 0)
);

CREATE TABLE IF NOT EXISTS game_platforms (
    game_id BIGINT NOT NULL,
    platform_id BIGINT NOT NULL,
    release_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'available',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT game_platforms_pk PRIMARY KEY (game_id, platform_id),
    CONSTRAINT game_platforms_game_fk
        FOREIGN KEY (game_id) REFERENCES games (id) ON DELETE CASCADE,
    CONSTRAINT game_platforms_platform_fk
        FOREIGN KEY (platform_id) REFERENCES platforms (id) ON DELETE RESTRICT,
    CONSTRAINT game_platforms_status_valid
        CHECK (status IN ('planned', 'available', 'retired')),
    CONSTRAINT game_platforms_release_date_valid
        CHECK (release_date >= DATE '1970-01-01')
);

ALTER TABLE platforms
    ADD COLUMN IF NOT EXISTS manufacturer VARCHAR(80);

UPDATE platforms
SET manufacturer = COALESCE(manufacturer, 'Unknown')
WHERE manufacturer IS NULL;

ALTER TABLE platforms
    ALTER COLUMN manufacturer SET NOT NULL;

ALTER TABLE game_platforms
    ADD COLUMN IF NOT EXISTS release_date DATE,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'available';

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'game_platforms' AND column_name = 'released_at') THEN
        UPDATE game_platforms
        SET release_date = COALESCE(release_date, released_at::date)
        WHERE release_date IS NULL;
    END IF;
END
$$;

UPDATE game_platforms
SET release_date = DATE '1970-01-01'
WHERE release_date IS NULL;

UPDATE game_platforms
SET status = 'available'
WHERE status IS NULL;

ALTER TABLE game_platforms
    ALTER COLUMN release_date SET NOT NULL,
    ALTER COLUMN status SET NOT NULL;

CREATE TABLE IF NOT EXISTS metric_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    metric_name VARCHAR(30) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    description VARCHAR(200) NOT NULL,

    CONSTRAINT metric_definitions_name_unique UNIQUE (metric_name),
    CONSTRAINT metric_definitions_name_unit_unique UNIQUE (metric_name, unit),
    CONSTRAINT metric_definitions_name_not_blank CHECK (length(trim(metric_name)) > 0),
    CONSTRAINT metric_definitions_unit_not_blank CHECK (length(trim(unit)) > 0),
    CONSTRAINT metric_definitions_description_not_blank CHECK (length(trim(description)) > 0)
);

-- Upgrade databases created by the first M02 draft, which used code/min_value/max_value.
ALTER TABLE metric_definitions
    ADD COLUMN IF NOT EXISTS metric_name VARCHAR(30),
    ADD COLUMN IF NOT EXISTS description VARCHAR(200);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'metric_definitions'
          AND column_name = 'code'
    ) THEN
        UPDATE metric_definitions
        SET metric_name = COALESCE(metric_name, code)
        WHERE metric_name IS NULL;
    END IF;

    UPDATE metric_definitions
    SET description = COALESCE(description, 'Definicion de metrica CDRL')
    WHERE description IS NULL;
END
$$;

ALTER TABLE metric_definitions
    ALTER COLUMN metric_name SET NOT NULL,
    ALTER COLUMN description SET NOT NULL;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'metric_definitions' AND column_name = 'code') THEN
        ALTER TABLE metric_definitions ALTER COLUMN code DROP NOT NULL;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'metric_definitions' AND column_name = 'min_value') THEN
        ALTER TABLE metric_definitions ALTER COLUMN min_value DROP NOT NULL;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'metric_definitions' AND column_name = 'max_value') THEN
        ALTER TABLE metric_definitions ALTER COLUMN max_value DROP NOT NULL;
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'metric_definitions_name_unique'
          AND conrelid = 'metric_definitions'::regclass
    ) THEN
        ALTER TABLE metric_definitions
            ADD CONSTRAINT metric_definitions_name_unique UNIQUE (metric_name);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'metric_definitions_name_unit_unique'
          AND conrelid = 'metric_definitions'::regclass
    ) THEN
        ALTER TABLE metric_definitions
            ADD CONSTRAINT metric_definitions_name_unit_unique UNIQUE (metric_name, unit);
    END IF;
END
$$;

INSERT INTO metric_definitions (metric_name, unit, description)
VALUES
    ('duration', 'hours', 'Horas estimadas de juego'),
    ('rating', 'stars', 'Calificacion promedio de usuarios')
ON CONFLICT (metric_name) DO NOTHING;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'game_metrics_metric_definition_fk'
          AND conrelid = 'game_metrics'::regclass
    ) THEN
        ALTER TABLE game_metrics
            ADD CONSTRAINT game_metrics_metric_definition_fk
            FOREIGN KEY (metric_name, unit)
            REFERENCES metric_definitions (metric_name, unit)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_game_platforms_platform_id
    ON game_platforms (platform_id);

CREATE INDEX IF NOT EXISTS idx_game_platforms_release_date
    ON game_platforms (release_date);

CREATE INDEX IF NOT EXISTS idx_metric_definitions_name
    ON metric_definitions (metric_name);